# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Member(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, name: str=None, phone_number: str=None, address: str=None):  # noqa: E501
        """Member - a model defined in Swagger

        :param id: The id of this Member.  # noqa: E501
        :type id: int
        :param name: The name of this Member.  # noqa: E501
        :type name: str
        :param phone_number: The phone_number of this Member.  # noqa: E501
        :type phone_number: str
        :param address: The address of this Member.  # noqa: E501
        :type address: str
        """
        self.swagger_types = {
            'id': int,
            'name': str,
            'phone_number': str,
            'address': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'phone_number': 'phone_number',
            'address': 'address'
        }
        self._id = id
        self._name = name
        self._phone_number = phone_number
        self._address = address

    @classmethod
    def from_dict(cls, dikt) -> 'Member':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Member of this Member.  # noqa: E501
        :rtype: Member
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Member.

        Member ID  # noqa: E501

        :return: The id of this Member.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Member.

        Member ID  # noqa: E501

        :param id: The id of this Member.
        :type id: int
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this Member.

        Họ và tên  # noqa: E501

        :return: The name of this Member.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Member.

        Họ và tên  # noqa: E501

        :param name: The name of this Member.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def phone_number(self) -> str:
        """Gets the phone_number of this Member.

        Số điện thoại  # noqa: E501

        :return: The phone_number of this Member.
        :rtype: str
        """
        return self._phone_number

    @phone_number.setter
    def phone_number(self, phone_number: str):
        """Sets the phone_number of this Member.

        Số điện thoại  # noqa: E501

        :param phone_number: The phone_number of this Member.
        :type phone_number: str
        """
        if phone_number is None:
            raise ValueError("Invalid value for `phone_number`, must not be `None`")  # noqa: E501

        self._phone_number = phone_number

    @property
    def address(self) -> str:
        """Gets the address of this Member.

        Địa chỉ  # noqa: E501

        :return: The address of this Member.
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address: str):
        """Sets the address of this Member.

        Địa chỉ  # noqa: E501

        :param address: The address of this Member.
        :type address: str
        """
        if address is None:
            raise ValueError("Invalid value for `address`, must not be `None`")  # noqa: E501

        self._address = address
